In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
BASE_DIR = "/content/drive/MyDrive/DL_Final_Project"

import os
import sys

sys.path.extend([os.getcwd(), os.path.join(os.getcwd(), "notebook")])

print(os.listdir("/content/drive/MyDrive/DL_Final_Project"))

['weather_data', 'electricity_data', 'supervised.ipynb', 'Fine_Tuning.ipynb', 'Lin_Prob.ipynb', 'main.ipynb']

In [ ]:
import pandas as pd

WEATHER_DIR = f"{BASE_DIR}/weather_data"

files = [f for f in os.listdir(WEATHER_DIR)]
print(files)

path = os.path.join(WEATHER_DIR, files[0])
df = pd.read_csv(path, encoding="latin1")

print(df.shape)
display(df.head())
print(df.dtypes)

['mpi_roof_2025.csv']
(52560, 22)

,Date Time,p (mbar),T (degC),Tpot (K),Tdew (degC),rh (%),VPmax (mbar),VPact (mbar),VPdef (mbar),sh (g/kg),...,wv (m/s),max. wv (m/s),wd (deg),rain (mm),raining (s),SWDR (W/m²),PAR (µmol/m²/s),max. PAR (µmol/m²/s),Tlog (degC),CO2 (ppm)
0,01.01.2025 00:10:00,997.30,-1.56,271.80,-2.97,90.0,5.45,4.90,0.54,3.06,...,1.61,3.87,148.9,0.0,0.0,0.0,0.0,0.0,6.24,456.9
1,01.01.2025 00:20:00,997.05,-0.90,272.48,-2.66,87.8,5.72,5.02,0.70,3.14,...,1.71,3.05,145.6,0.0,0.0,0.0,0.0,0.0,6.32,451.7
2,01.01.2025 00:30:00,996.96,-0.51,272.88,-2.44,86.7,5.89,5.10,0.78,3.19,...,1.61,3.31,146.9,0.0,0.0,0.0,0.0,0.0,6.46,451.0
3,01.01.2025 00:40:00,996.77,-0.27,273.14,-2.26,86.3,5.99,5.17,0.82,3.23,...,1.86,2.93,137.0,0.0,0.0,0.0,0.0,0.0,6.63,450.4
4,01.01.2025 00:50:00,996.62,-0.09,273.33,-2.14,86.0,6.07,5.22,0.85,3.26,...,1.25,2.23,131.3,0.0,0.0,0.0,0.0,0.0,6.82,450.4

Date Time                object
p (mbar)                float64
T (degC)                float64
Tpot (K)                float64
Tdew (degC)             float64
rh (%)                  float64
VPmax (mbar)            float64
VPact (mbar)            float64
VPdef (mbar)            float64
sh (g/kg)               float64
H2OC (mmol/mol)         float64
rho (g/m**3)            float64
wv (m/s)                float64
max. wv (m/s)           float64
wd (deg)                float64
rain (mm)               float64
raining (s)             float64
SWDR (W/m²)             float64
PAR (µmol/m²/s)         float64
max. PAR (µmol/m²/s)    float64
Tlog (degC)             float64
CO2 (ppm)               float64
dtype: object

In [ ]:
print(df.shape)
print(df.columns.tolist())
print(df.dtypes)
df.isna().sum().sort_values(ascending=False).head(20)

(52560, 22)
['Date Time', 'p (mbar)', 'T (degC)', 'Tpot (K)', 'Tdew (degC)', 'rh (%)', 'VPmax (mbar)', 'VPact (mbar)', 'VPdef (mbar)', 'sh (g/kg)', 'H2OC (mmol/mol)', 'rho (g/m**3)', 'wv (m/s)', 'max. wv (m/s)', 'wd (deg)', 'rain (mm)', 'raining (s)', 'SWDR (W/m²)', 'PAR (µmol/m²/s)', 'max. PAR (µmol/m²/s)', 'Tlog (degC)', 'CO2 (ppm)']
Date Time                object
p (mbar)                float64
T (degC)                float64
Tpot (K)                float64
Tdew (degC)             float64
rh (%)                  float64
VPmax (mbar)            float64
VPact (mbar)            float64
VPdef (mbar)            float64
sh (g/kg)               float64
H2OC (mmol/mol)         float64
rho (g/m**3)            float64
wv (m/s)                float64
max. wv (m/s)           float64
wd (deg)                float64
rain (mm)               float64
raining (s)             float64
SWDR (W/m²)             float64
PAR (µmol/m²/s)         float64
max. PAR (µmol/m²/s)    float64
Tlog (degC)             float64
CO2 (ppm)               float64
dtype: object

Date Time               0
p (mbar)                0
T (degC)                0
Tpot (K)                0
Tdew (degC)             0
rh (%)                  0
VPmax (mbar)            0
VPact (mbar)            0
VPdef (mbar)            0
sh (g/kg)               0
H2OC (mmol/mol)         0
rho (g/m**3)            0
wv (m/s)                0
max. wv (m/s)           0
wd (deg)                0
rain (mm)               0
raining (s)             0
SWDR (W/m²)             0
PAR (µmol/m²/s)         0
max. PAR (µmol/m²/s)    0
dtype: int64

In [ ]:
import os
import sys

sys.path.extend([os.getcwd(), os.path.join(os.getcwd(), "notebook")])

from helpers.data import load_weather, load_electricity, split_and_scale

Bad timestamps: 0
0   2025-01-01 00:10:00
1   2025-01-01 00:20:00
2   2025-01-01 00:30:00
3   2025-01-01 00:40:00
4   2025-01-01 00:50:00
Name: Date Time, dtype: datetime64[ns]
Date Time
0 days 00:10:00    52559
Name: count, dtype: int64

In [ ]:
# 1. Define the split ratios
n = len(df)
train_end = int(n * 0.7)
val_end = int(n * 0.8) # 70% to 80% is the 10% validation slice

# 2. Split the dataframe
# We keep the raw data for now; we'll handle normalization next
train_df = df.iloc[:train_end]
val_df = df.iloc[train_end:val_end]
test_df = df.iloc[val_end:]

print(f"Total records: {n}")
print(f"Train set: {len(train_df)} rows")
print(f"Val set:   {len(val_df)} rows")
print(f"Test set:  {len(test_df)} rows")

# 3. Separate features from the timestamp
# The 'Date Time' column isn't a feature the model processes directly
# We'll need it for plotting later, but for the Transformer, we focus on the values.
cols_to_drop = [time_col]
features = [c for c in df.columns if c not in cols_to_drop]

print(f"\nNumber of features to be used: {len(features)}")

Total records: 52560
Train set: 36792 rows
Val set:   5256 rows
Test set:  10512 rows

Number of features to be used: 21

In [ ]:
from helpers.datasets import WeatherDataset
from helpers.models import PatchEmbedding, RevIN, PatchTST_SelfSupervised, PatchTST_Supervised
import torch
from torch.utils.data import DataLoader

# --- Implementation Example ---
# Assuming 'train_df', 'val_df', and 'test_df' are ready from your preprocessing block
# and 'features' contains the list of column names you are using.

seq_len = 512  # Set by the paper for representation learning experiments
pred_len = 96  # Start with T=96 as per Table 4

# Initialize datasets
train_dataset = WeatherDataset(train_df[features], seq_len, pred_len)
val_dataset = WeatherDataset(val_df[features], seq_len, pred_len)
test_dataset = WeatherDataset(test_df[features], seq_len, pred_len)

# Initialize dataloaders
batch_size = 128
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, drop_last=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

print(f"Number of training batches: {len(train_loader)}")

Number of training batches: 282

In [ ]:
from helpers.training import pretrain_model
from helpers.training import EarlyStopping
from helpers.training import pretrain_model_with_es
from helpers.training import linear_probing_with_es

import torch
import pandas as pd

pred_lengths = [96, 192, 336, 720]
seq_len = 512
batch_size = 128
results_summary = {"Horizon": [], "Val MSE": [], "Val MAE": []}

print("=== PHASE 1: Self-Supervised Pre-Training (Weather) ===")
train_dataset_ssl = WeatherDataset(train_df[features], seq_len, pred_len=96)
val_dataset_ssl = WeatherDataset(val_df[features], seq_len, pred_len=96)
train_loader_ssl = DataLoader(train_dataset_ssl, batch_size=batch_size, shuffle=True, drop_last=True)
val_loader_ssl = DataLoader(val_dataset_ssl, batch_size=batch_size, shuffle=False)

model_ssl = PatchTST_SelfSupervised(num_features=len(features), seq_len=seq_len, patch_len=12, stride=12)
# Using pretrain_model_with_es to handle the 100 epoch limit efficiently
trained_ssl_model = pretrain_model_with_es(model_ssl, train_loader_ssl, val_loader_ssl, epochs=100, lr=1e-4, patience=10)

print("\n=== PHASE 2: Linear Probing (Weather) ===")
for pred_len in pred_lengths:
    print(f"\n--- Horizon: T={pred_len} ---")
    train_dataset = WeatherDataset(train_df[features], seq_len, pred_len)
    val_dataset = WeatherDataset(val_df[features], seq_len, pred_len)
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, drop_last=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

    model_sup = PatchTST_Supervised(num_features=len(features), seq_len=seq_len, pred_len=pred_len, patch_len=12, stride=12)
    trained_sup_model = linear_probing_with_es(model_sup, trained_ssl_model, train_loader, val_loader, epochs=20, lr=1e-4, patience=5)

    trained_sup_model.eval()
    mse_crit, mae_crit = nn.MSELoss(), nn.L1Loss()
    v_mse, v_mae = 0.0, 0.0
    with torch.no_grad():
        for bx, by in val_loader:
            bx, by = bx.to(device), by.to(device)
            preds = trained_sup_model(bx)
            v_mse += mse_crit(preds, by).item()
            v_mae += mae_crit(preds, by).item()

    results_summary["Horizon"].append(pred_len)
    results_summary["Val MSE"].append(v_mse / len(val_loader))
    results_summary["Val MAE"].append(v_mae / len(val_loader))

print("\nFINAL RESULTS (WEATHER)")
print(pd.DataFrame(results_summary).set_index("Horizon").round(3))

=== PHASE 1: Self-Supervised Pre-Training (Weather) ===

Epoch 1/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.79it/s]

Epoch 1 | Train Loss: 0.7937 | Val Loss: 0.4596

Epoch 2/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.83it/s]

Epoch 2 | Train Loss: 0.4016 | Val Loss: 0.3264

Epoch 3/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.81it/s]

Epoch 3 | Train Loss: 0.3198 | Val Loss: 0.2589

Epoch 4/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.79it/s]

Epoch 4 | Train Loss: 0.2742 | Val Loss: 0.2324

Epoch 5/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.79it/s]

Epoch 5 | Train Loss: 0.2485 | Val Loss: 0.2150

Epoch 6/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 6 | Train Loss: 0.2290 | Val Loss: 0.1981

Epoch 7/100 [Pre-train]: 100%|██████████| 282/282 [00:59<00:00,  4.78it/s]

Epoch 7 | Train Loss: 0.2115 | Val Loss: 0.1844

Epoch 8/100 [Pre-train]: 100%|██████████| 282/282 [00:59<00:00,  4.78it/s]

Epoch 8 | Train Loss: 0.1969 | Val Loss: 0.1725

Epoch 9/100 [Pre-train]: 100%|██████████| 282/282 [00:59<00:00,  4.77it/s]

Epoch 9 | Train Loss: 0.1830 | Val Loss: 0.1612

Epoch 10/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 10 | Train Loss: 0.1703 | Val Loss: 0.1494

Epoch 11/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 11 | Train Loss: 0.1582 | Val Loss: 0.1394

Epoch 12/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 12 | Train Loss: 0.1467 | Val Loss: 0.1301

Epoch 13/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 13 | Train Loss: 0.1363 | Val Loss: 0.1200

Epoch 14/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 14 | Train Loss: 0.1260 | Val Loss: 0.1104

Epoch 15/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 15 | Train Loss: 0.1160 | Val Loss: 0.1020

Epoch 16/100 [Pre-train]: 100%|██████████| 282/282 [00:59<00:00,  4.78it/s]

Epoch 16 | Train Loss: 0.1063 | Val Loss: 0.0929

Epoch 17/100 [Pre-train]: 100%|██████████| 282/282 [00:59<00:00,  4.78it/s]

Epoch 17 | Train Loss: 0.0976 | Val Loss: 0.0848

Epoch 18/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 18 | Train Loss: 0.0892 | Val Loss: 0.0772

Epoch 19/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 19 | Train Loss: 0.0816 | Val Loss: 0.0711

Epoch 20/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 20 | Train Loss: 0.0743 | Val Loss: 0.0642

Epoch 21/100 [Pre-train]: 100%|██████████| 282/282 [00:59<00:00,  4.78it/s]

Epoch 21 | Train Loss: 0.0680 | Val Loss: 0.0592

Epoch 22/100 [Pre-train]: 100%|██████████| 282/282 [00:59<00:00,  4.78it/s]

Epoch 22 | Train Loss: 0.0618 | Val Loss: 0.0539

Epoch 23/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 23 | Train Loss: 0.0563 | Val Loss: 0.0489

Epoch 24/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 24 | Train Loss: 0.0510 | Val Loss: 0.0444

Epoch 25/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 25 | Train Loss: 0.0461 | Val Loss: 0.0400

Epoch 26/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 26 | Train Loss: 0.0416 | Val Loss: 0.0356

Epoch 27/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 27 | Train Loss: 0.0373 | Val Loss: 0.0322

Epoch 28/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 28 | Train Loss: 0.0334 | Val Loss: 0.0289

Epoch 29/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 29 | Train Loss: 0.0297 | Val Loss: 0.0255

Epoch 30/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 30 | Train Loss: 0.0263 | Val Loss: 0.0224

Epoch 31/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 31 | Train Loss: 0.0231 | Val Loss: 0.0195

Epoch 32/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 32 | Train Loss: 0.0202 | Val Loss: 0.0171

Epoch 33/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 33 | Train Loss: 0.0175 | Val Loss: 0.0147

Epoch 34/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 34 | Train Loss: 0.0151 | Val Loss: 0.0127

Epoch 35/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 35 | Train Loss: 0.0129 | Val Loss: 0.0107

Epoch 36/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 36 | Train Loss: 0.0109 | Val Loss: 0.0090

Epoch 37/100 [Pre-train]: 100%|██████████| 282/282 [00:59<00:00,  4.78it/s]

Epoch 37 | Train Loss: 0.0092 | Val Loss: 0.0074

Epoch 38/100 [Pre-train]: 100%|██████████| 282/282 [00:59<00:00,  4.78it/s]

Epoch 38 | Train Loss: 0.0076 | Val Loss: 0.0061

Epoch 39/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 39 | Train Loss: 0.0063 | Val Loss: 0.0050

Epoch 40/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 40 | Train Loss: 0.0051 | Val Loss: 0.0040

Epoch 41/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 41 | Train Loss: 0.0041 | Val Loss: 0.0031

Epoch 42/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 42 | Train Loss: 0.0032 | Val Loss: 0.0025

Epoch 43/100 [Pre-train]: 100%|██████████| 282/282 [00:59<00:00,  4.78it/s]

Epoch 43 | Train Loss: 0.0025 | Val Loss: 0.0019

Epoch 44/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 44 | Train Loss: 0.0019 | Val Loss: 0.0014

Epoch 45/100 [Pre-train]: 100%|██████████| 282/282 [00:59<00:00,  4.78it/s]

Epoch 45 | Train Loss: 0.0015 | Val Loss: 0.0011

Epoch 46/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 46 | Train Loss: 0.0011 | Val Loss: 0.0008

Epoch 47/100 [Pre-train]: 100%|██████████| 282/282 [00:59<00:00,  4.78it/s]

Epoch 47 | Train Loss: 0.0008 | Val Loss: 0.0006

Epoch 48/100 [Pre-train]: 100%|██████████| 282/282 [00:59<00:00,  4.78it/s]

Epoch 48 | Train Loss: 0.0006 | Val Loss: 0.0004

Epoch 49/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 49 | Train Loss: 0.0004 | Val Loss: 0.0003

Epoch 50/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 50 | Train Loss: 0.0003 | Val Loss: 0.0002

Epoch 51/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 51 | Train Loss: 0.0002 | Val Loss: 0.0001

Epoch 52/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 52 | Train Loss: 0.0001 | Val Loss: 0.0001

Epoch 53/100 [Pre-train]: 100%|██████████| 282/282 [00:59<00:00,  4.78it/s]

Epoch 53 | Train Loss: 0.0001 | Val Loss: 0.0000

Epoch 54/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 54 | Train Loss: 0.0000 | Val Loss: 0.0000

Epoch 55/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 55 | Train Loss: 0.0000 | Val Loss: 0.0000

Epoch 56/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 56 | Train Loss: 0.0000 | Val Loss: 0.0000

Epoch 57/100 [Pre-train]: 100%|██████████| 282/282 [00:59<00:00,  4.78it/s]

Epoch 57 | Train Loss: 0.0000 | Val Loss: 0.0000

Epoch 58/100 [Pre-train]: 100%|██████████| 282/282 [00:59<00:00,  4.78it/s]

Epoch 58 | Train Loss: 0.0000 | Val Loss: 0.0000

Epoch 59/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 59 | Train Loss: 0.0000 | Val Loss: 0.0000

Epoch 60/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 60 | Train Loss: 0.0000 | Val Loss: 0.0000

Epoch 61/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 61 | Train Loss: 0.0000 | Val Loss: 0.0000

Epoch 62/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 62 | Train Loss: 0.0000 | Val Loss: 0.0000

Epoch 63/100 [Pre-train]: 100%|██████████| 282/282 [00:59<00:00,  4.78it/s]

Epoch 63 | Train Loss: 0.0000 | Val Loss: 0.0000
EarlyStopping counter: 1 out of 10

Epoch 64/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 64 | Train Loss: 0.0000 | Val Loss: 0.0000

Epoch 65/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 65 | Train Loss: 0.0000 | Val Loss: 0.0000
EarlyStopping counter: 1 out of 10

Epoch 66/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.79it/s]

Epoch 66 | Train Loss: 0.0000 | Val Loss: 0.0000

Epoch 67/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 67 | Train Loss: 0.0000 | Val Loss: 0.0000
EarlyStopping counter: 1 out of 10

Epoch 68/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 68 | Train Loss: 0.0000 | Val Loss: 0.0000

Epoch 69/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 69 | Train Loss: 0.0000 | Val Loss: 0.0000

Epoch 70/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 70 | Train Loss: 0.0000 | Val Loss: 0.0000
EarlyStopping counter: 1 out of 10

Epoch 71/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 71 | Train Loss: 0.0000 | Val Loss: 0.0000
EarlyStopping counter: 2 out of 10

Epoch 72/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 72 | Train Loss: 0.0000 | Val Loss: 0.0000
EarlyStopping counter: 3 out of 10

Epoch 73/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 73 | Train Loss: 0.0000 | Val Loss: 0.0000
EarlyStopping counter: 4 out of 10

Epoch 74/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 74 | Train Loss: 0.0000 | Val Loss: 0.0000
EarlyStopping counter: 5 out of 10

Epoch 75/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 75 | Train Loss: 0.0000 | Val Loss: 0.0000
EarlyStopping counter: 6 out of 10

Epoch 76/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 76 | Train Loss: 0.0000 | Val Loss: 0.0000
EarlyStopping counter: 7 out of 10

Epoch 77/100 [Pre-train]: 100%|██████████| 282/282 [00:59<00:00,  4.78it/s]

Epoch 77 | Train Loss: 0.0000 | Val Loss: 0.0000
EarlyStopping counter: 8 out of 10

Epoch 78/100 [Pre-train]: 100%|██████████| 282/282 [00:59<00:00,  4.78it/s]

Epoch 78 | Train Loss: 0.0000 | Val Loss: 0.0000
EarlyStopping counter: 9 out of 10

Epoch 79/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 79 | Train Loss: 0.0000 | Val Loss: 0.0000

Epoch 80/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 80 | Train Loss: 0.0000 | Val Loss: 0.0000
EarlyStopping counter: 1 out of 10

Epoch 81/100 [Pre-train]: 100%|██████████| 282/282 [00:59<00:00,  4.78it/s]

Epoch 81 | Train Loss: 0.0000 | Val Loss: 0.0000

Epoch 82/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 82 | Train Loss: 0.0000 | Val Loss: 0.0000
EarlyStopping counter: 1 out of 10

Epoch 83/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 83 | Train Loss: 0.0000 | Val Loss: 0.0000
EarlyStopping counter: 2 out of 10

Epoch 84/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 84 | Train Loss: 0.0000 | Val Loss: 0.0000
EarlyStopping counter: 3 out of 10

Epoch 85/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 85 | Train Loss: 0.0000 | Val Loss: 0.0000
EarlyStopping counter: 4 out of 10

Epoch 86/100 [Pre-train]: 100%|██████████| 282/282 [00:59<00:00,  4.78it/s]

Epoch 86 | Train Loss: 0.0000 | Val Loss: 0.0000
EarlyStopping counter: 5 out of 10

Epoch 87/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 87 | Train Loss: 0.0000 | Val Loss: 0.0000
EarlyStopping counter: 6 out of 10

Epoch 88/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 88 | Train Loss: 0.0000 | Val Loss: 0.0000
EarlyStopping counter: 7 out of 10

Epoch 89/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 89 | Train Loss: 0.0000 | Val Loss: 0.0000
EarlyStopping counter: 8 out of 10

Epoch 90/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 90 | Train Loss: 0.0000 | Val Loss: 0.0000
EarlyStopping counter: 9 out of 10

Epoch 91/100 [Pre-train]: 100%|██████████| 282/282 [00:58<00:00,  4.78it/s]

Epoch 91 | Train Loss: 0.0000 | Val Loss: 0.0000
EarlyStopping counter: 10 out of 10
Early stopping triggered!

=== PHASE 2: Linear Probing (Weather) ===

--- Horizon: T=96 ---

Epoch 1/20 [Linear Probing]: 100%|██████████| 282/282 [00:18<00:00, 14.90it/s]

Epoch 1 | Train MSE: 23429003432974120.0000 | Val MSE: 96952286573097.5156 | Val MAE: 2518810.0912

Epoch 2/20 [Linear Probing]: 100%|██████████| 282/282 [00:18<00:00, 14.92it/s]

Epoch 2 | Train MSE: 9670331890468210.0000 | Val MSE: 38937356778191.5703 | Val MAE: 1669717.0034

Epoch 3/20 [Linear Probing]: 100%|██████████| 282/282 [00:18<00:00, 14.92it/s]

Epoch 3 | Train MSE: 4172952945581673.5000 | Val MSE: 19812922914207.1367 | Val MAE: 1272342.1926

Epoch 4/20 [Linear Probing]: 100%|██████████| 282/282 [00:18<00:00, 14.92it/s]

Epoch 4 | Train MSE: 2063010768093184.0000 | Val MSE: 23962992990706.1641 | Val MAE: 1280537.3598
EarlyStopping counter: 1 out of 5

Epoch 5/20 [Linear Probing]: 100%|██████████| 282/282 [00:18<00:00, 14.94it/s]

Epoch 5 | Train MSE: 1176721136137150.7500 | Val MSE: 15952683211692.9727 | Val MAE: 1116578.0676

Epoch 6/20 [Linear Probing]: 100%|██████████| 282/282 [00:18<00:00, 14.93it/s]

Epoch 6 | Train MSE: 743710742172548.5000 | Val MSE: 16089697732774.0547 | Val MAE: 1120315.1976
EarlyStopping counter: 1 out of 5

Epoch 7/20 [Linear Probing]: 100%|██████████| 282/282 [00:18<00:00, 14.92it/s]

Epoch 7 | Train MSE: 497907091009681.2500 | Val MSE: 9746231456297.5137 | Val MAE: 811355.8818

Epoch 8/20 [Linear Probing]: 100%|██████████| 282/282 [00:18<00:00, 14.93it/s]

Epoch 8 | Train MSE: 339466905266626.2500 | Val MSE: 9151701978582.4863 | Val MAE: 825768.1470

Epoch 9/20 [Linear Probing]: 100%|██████████| 282/282 [00:18<00:00, 14.92it/s]

Epoch 9 | Train MSE: 235672007979966.6250 | Val MSE: 5319450342372.3242 | Val MAE: 633204.2492

Epoch 10/20 [Linear Probing]: 100%|██████████| 282/282 [00:18<00:00, 14.94it/s]

Epoch 10 | Train MSE: 164281637841578.6562 | Val MSE: 5996509241122.5947 | Val MAE: 659844.8860
EarlyStopping counter: 1 out of 5

Epoch 11/20 [Linear Probing]: 100%|██████████| 282/282 [00:18<00:00, 14.94it/s]

Epoch 11 | Train MSE: 113998931568625.4688 | Val MSE: 4433884366128.4326 | Val MAE: 563969.1562

Epoch 12/20 [Linear Probing]: 100%|██████████| 282/282 [00:18<00:00, 14.93it/s]

Epoch 12 | Train MSE: 78844465759718.5781 | Val MSE: 7079118422458.8105 | Val MAE: 754459.0743
EarlyStopping counter: 1 out of 5

Epoch 13/20 [Linear Probing]: 100%|██████████| 282/282 [00:18<00:00, 14.93it/s]

Epoch 13 | Train MSE: 54783989181447.2656 | Val MSE: 3137817259257.0811 | Val MAE: 475281.0034

Epoch 14/20 [Linear Probing]: 100%|██████████| 282/282 [00:18<00:00, 14.93it/s]

Epoch 14 | Train MSE: 38331567998554.7812 | Val MSE: 3917171321662.2705 | Val MAE: 540151.8615
EarlyStopping counter: 1 out of 5

Epoch 15/20 [Linear Probing]: 100%|██████████| 282/282 [00:18<00:00, 14.92it/s]

Epoch 15 | Train MSE: 27713883424462.9805 | Val MSE: 3395088680683.2432 | Val MAE: 468683.1765
EarlyStopping counter: 2 out of 5

Epoch 16/20 [Linear Probing]: 100%|██████████| 282/282 [00:18<00:00, 14.92it/s]

Epoch 16 | Train MSE: 20642033593583.6602 | Val MSE: 2504068233492.7568 | Val MAE: 432450.2200

Epoch 17/20 [Linear Probing]: 100%|██████████| 282/282 [00:18<00:00, 14.91it/s]

Epoch 17 | Train MSE: 19360023649083.9141 | Val MSE: 2437077327207.7837 | Val MAE: 398895.1579

Epoch 18/20 [Linear Probing]: 100%|██████████| 282/282 [00:18<00:00, 14.91it/s]

Epoch 18 | Train MSE: 16493865598976.0000 | Val MSE: 4387159249228.1079 | Val MAE: 555912.7889
EarlyStopping counter: 1 out of 5

Epoch 19/20 [Linear Probing]: 100%|██████████| 282/282 [00:18<00:00, 14.95it/s]

Epoch 19 | Train MSE: 17587407650118.8086 | Val MSE: 2910185556576.8647 | Val MAE: 411457.9641
EarlyStopping counter: 2 out of 5

Epoch 20/20 [Linear Probing]: 100%|██████████| 282/282 [00:18<00:00, 14.92it/s]

Epoch 20 | Train MSE: 16979220787345.2480 | Val MSE: 3118929559109.1890 | Val MAE: 453282.2872
EarlyStopping counter: 3 out of 5

--- Horizon: T=192 ---

Epoch 1/20 [Linear Probing]: 100%|██████████| 281/281 [00:19<00:00, 14.75it/s]

Epoch 1 | Train MSE: 24109551978403352.0000 | Val MSE: 79140269646734.2188 | Val MAE: 2379209.1146

Epoch 2/20 [Linear Probing]: 100%|██████████| 281/281 [00:19<00:00, 14.78it/s]

Epoch 2 | Train MSE: 10317848790433792.0000 | Val MSE: 54416144451356.4453 | Val MAE: 1950999.1944

Epoch 3/20 [Linear Probing]: 100%|██████████| 281/281 [00:19<00:00, 14.77it/s]

Epoch 3 | Train MSE: 4647610079504931.0000 | Val MSE: 28986568649386.6680 | Val MAE: 1443398.4688

Epoch 4/20 [Linear Probing]: 100%|██████████| 281/281 [00:19<00:00, 14.76it/s]

Epoch 4 | Train MSE: 2342492995090497.5000 | Val MSE: 20970895208903.1094 | Val MAE: 1226348.4861

Epoch 5/20 [Linear Probing]: 100%|██████████| 281/281 [00:19<00:00, 14.78it/s]

Epoch 5 | Train MSE: 1340325230587627.0000 | Val MSE: 13736090009600.0000 | Val MAE: 988476.3455

Epoch 6/20 [Linear Probing]: 100%|██████████| 281/281 [00:19<00:00, 14.77it/s]

Epoch 6 | Train MSE: 839633926115371.7500 | Val MSE: 12943278975658.6660 | Val MAE: 927088.6319

Epoch 7/20 [Linear Probing]: 100%|██████████| 281/281 [00:19<00:00, 14.76it/s]

Epoch 7 | Train MSE: 557892060557268.2500 | Val MSE: 7239194982627.5557 | Val MAE: 696563.3663

Epoch 8/20 [Linear Probing]: 100%|██████████| 281/281 [00:19<00:00, 14.76it/s]

Epoch 8 | Train MSE: 382291036009045.6250 | Val MSE: 8169441005112.8887 | Val MAE: 775663.1016
EarlyStopping counter: 1 out of 5

Epoch 9/20 [Linear Probing]: 100%|██████████| 281/281 [00:19<00:00, 14.77it/s]

Epoch 9 | Train MSE: 265175380048345.7500 | Val MSE: 6396360611157.3330 | Val MAE: 652810.8568

Epoch 10/20 [Linear Probing]: 100%|██████████| 281/281 [00:19<00:00, 14.74it/s]

Epoch 10 | Train MSE: 186859185481866.4688 | Val MSE: 5363216817265.7773 | Val MAE: 617327.3594

Epoch 11/20 [Linear Probing]: 100%|██████████| 281/281 [00:19<00:00, 14.76it/s]

Epoch 11 | Train MSE: 131043571007488.0000 | Val MSE: 5352611130026.6670 | Val MAE: 601335.1024

Epoch 12/20 [Linear Probing]: 100%|██████████| 281/281 [00:19<00:00, 14.76it/s]

Epoch 12 | Train MSE: 91427911816960.9062 | Val MSE: 3155351042275.5557 | Val MAE: 473291.2144

Epoch 13/20 [Linear Probing]: 100%|██████████| 281/281 [00:19<00:00, 14.75it/s]

Epoch 13 | Train MSE: 64260982035058.7891 | Val MSE: 3209245629553.7778 | Val MAE: 465058.6858
EarlyStopping counter: 1 out of 5

Epoch 14/20 [Linear Probing]: 100%|██████████| 281/281 [00:19<00:00, 14.76it/s]

Epoch 14 | Train MSE: 44947197104813.0938 | Val MSE: 2976793355150.2222 | Val MAE: 458772.6484

Epoch 15/20 [Linear Probing]: 100%|██████████| 281/281 [00:19<00:00, 14.76it/s]

Epoch 15 | Train MSE: 32333354053238.4336 | Val MSE: 4163065486449.7778 | Val MAE: 534193.1128
EarlyStopping counter: 1 out of 5

Epoch 16/20 [Linear Probing]: 100%|██████████| 281/281 [00:19<00:00, 14.77it/s]

Epoch 16 | Train MSE: 25371336578292.1562 | Val MSE: 2487710779164.4443 | Val MAE: 405424.9123

Epoch 17/20 [Linear Probing]: 100%|██████████| 281/281 [00:19<00:00, 14.75it/s]

Epoch 17 | Train MSE: 19949246573673.6797 | Val MSE: 2839870055310.2222 | Val MAE: 435651.3468
EarlyStopping counter: 1 out of 5

Epoch 18/20 [Linear Probing]: 100%|██████████| 281/281 [00:19<00:00, 14.76it/s]

Epoch 18 | Train MSE: 17885896775599.8281 | Val MSE: 2810212534044.4443 | Val MAE: 447232.1788
EarlyStopping counter: 2 out of 5

Epoch 19/20 [Linear Probing]: 100%|██████████| 281/281 [00:19<00:00, 14.75it/s]

Epoch 19 | Train MSE: 18765017134295.0039 | Val MSE: 3457532734122.6665 | Val MAE: 479432.6502
EarlyStopping counter: 3 out of 5

Epoch 20/20 [Linear Probing]: 100%|██████████| 281/281 [00:19<00:00, 14.75it/s]

Epoch 20 | Train MSE: 17935712203291.3320 | Val MSE: 2146465700977.7778 | Val MAE: 369374.5156

--- Horizon: T=336 ---

Epoch 1/20 [Linear Probing]: 100%|██████████| 280/280 [00:19<00:00, 14.35it/s]

Epoch 1 | Train MSE: 24569408248131468.0000 | Val MSE: 93249769427997.2500 | Val MAE: 2652389.0857

Epoch 2/20 [Linear Probing]: 100%|██████████| 280/280 [00:19<00:00, 14.35it/s]

Epoch 2 | Train MSE: 10844117190266998.0000 | Val MSE: 53472666575550.1719 | Val MAE: 1964462.6786

Epoch 3/20 [Linear Probing]: 100%|██████████| 280/280 [00:19<00:00, 14.35it/s]

Epoch 3 | Train MSE: 4943647016994172.0000 | Val MSE: 31469608377665.8281 | Val MAE: 1525229.7107

Epoch 4/20 [Linear Probing]: 100%|██████████| 280/280 [00:19<00:00, 14.38it/s]

Epoch 4 | Train MSE: 2487372598731454.0000 | Val MSE: 20921653874805.0273 | Val MAE: 1218583.9286

Epoch 5/20 [Linear Probing]: 100%|██████████| 280/280 [00:19<00:00, 14.35it/s]

Epoch 5 | Train MSE: 1412714998784702.2500 | Val MSE: 15396179931487.0859 | Val MAE: 1051908.5536

Epoch 6/20 [Linear Probing]: 100%|██████████| 280/280 [00:19<00:00, 14.34it/s]

Epoch 6 | Train MSE: 885973438318884.6250 | Val MSE: 13270363391356.3438 | Val MAE: 974841.8982

Epoch 7/20 [Linear Probing]: 100%|██████████| 280/280 [00:19<00:00, 14.36it/s]

Epoch 7 | Train MSE: 587467827318432.8750 | Val MSE: 9563742726670.6289 | Val MAE: 800953.0152

Epoch 8/20 [Linear Probing]: 100%|██████████| 280/280 [00:19<00:00, 14.35it/s]

Epoch 8 | Train MSE: 403779549239705.6250 | Val MSE: 7919231655701.9424 | Val MAE: 754712.1366

Epoch 9/20 [Linear Probing]: 100%|██████████| 280/280 [00:19<00:00, 14.36it/s]

Epoch 9 | Train MSE: 281972716444057.6250 | Val MSE: 6302379353234.2861 | Val MAE: 644435.1375

Epoch 10/20 [Linear Probing]: 100%|██████████| 280/280 [00:19<00:00, 14.36it/s]

Epoch 10 | Train MSE: 197888110928106.0625 | Val MSE: 5724656066325.9424 | Val MAE: 636821.8768

Epoch 11/20 [Linear Probing]: 100%|██████████| 280/280 [00:19<00:00, 14.35it/s]

Epoch 11 | Train MSE: 139336805387936.9219 | Val MSE: 4472764370592.9141 | Val MAE: 562093.0795

Epoch 12/20 [Linear Probing]: 100%|██████████| 280/280 [00:19<00:00, 14.36it/s]

Epoch 12 | Train MSE: 97837858085741.7188 | Val MSE: 4792339226389.9424 | Val MAE: 595904.0196
EarlyStopping counter: 1 out of 5

Epoch 13/20 [Linear Probing]: 100%|██████████| 280/280 [00:19<00:00, 14.34it/s]

Epoch 13 | Train MSE: 68645672744199.3125 | Val MSE: 3357359203006.1714 | Val MAE: 490616.5321

Epoch 14/20 [Linear Probing]: 100%|██████████| 280/280 [00:19<00:00, 14.35it/s]

Epoch 14 | Train MSE: 47950712701864.2266 | Val MSE: 3220705784627.2002 | Val MAE: 480694.3884

Epoch 15/20 [Linear Probing]: 100%|██████████| 280/280 [00:19<00:00, 14.38it/s]

Epoch 15 | Train MSE: 34067236093015.7695 | Val MSE: 3135528347706.5142 | Val MAE: 460899.2857

Epoch 16/20 [Linear Probing]: 100%|██████████| 280/280 [00:19<00:00, 14.37it/s]

Epoch 16 | Train MSE: 25661172905223.3125 | Val MSE: 2888670007413.0288 | Val MAE: 449895.7705

Epoch 17/20 [Linear Probing]: 100%|██████████| 280/280 [00:19<00:00, 14.35it/s]

Epoch 17 | Train MSE: 21023693438039.7695 | Val MSE: 7760862791972.5713 | Val MAE: 717563.1491
EarlyStopping counter: 1 out of 5

Epoch 18/20 [Linear Probing]: 100%|██████████| 280/280 [00:19<00:00, 14.37it/s]

Epoch 18 | Train MSE: 19944734720000.0000 | Val MSE: 1548281942601.1428 | Val MAE: 328435.9482

Epoch 19/20 [Linear Probing]: 100%|██████████| 280/280 [00:19<00:00, 14.33it/s]

Epoch 19 | Train MSE: 16072487472800.9141 | Val MSE: 2767866451909.4858 | Val MAE: 424203.7621
EarlyStopping counter: 1 out of 5

Epoch 20/20 [Linear Probing]: 100%|██████████| 280/280 [00:19<00:00, 14.34it/s]

Epoch 20 | Train MSE: 21298956550612.1133 | Val MSE: 9753807260408.6855 | Val MAE: 674987.0455
EarlyStopping counter: 2 out of 5

--- Horizon: T=720 ---

Epoch 1/20 [Linear Probing]: 100%|██████████| 277/277 [00:20<00:00, 13.51it/s]

Epoch 1 | Train MSE: 24565078555324372.0000 | Val MSE: 90217166274560.0000 | Val MAE: 2548309.6094

Epoch 2/20 [Linear Probing]: 100%|██████████| 277/277 [00:20<00:00, 13.55it/s]

Epoch 2 | Train MSE: 10842944535978842.0000 | Val MSE: 70424485920768.0000 | Val MAE: 2215421.0469

Epoch 3/20 [Linear Probing]: 100%|██████████| 277/277 [00:20<00:00, 13.52it/s]

Epoch 3 | Train MSE: 4941079452997344.0000 | Val MSE: 37924555046912.0000 | Val MAE: 1671033.7090

Epoch 4/20 [Linear Probing]: 100%|██████████| 277/277 [00:20<00:00, 13.54it/s]

Epoch 4 | Train MSE: 2487550456149284.0000 | Val MSE: 21067631329280.0000 | Val MAE: 1226111.8340

Epoch 5/20 [Linear Probing]: 100%|██████████| 277/277 [00:20<00:00, 13.53it/s]

Epoch 5 | Train MSE: 1412542452629385.7500 | Val MSE: 15777741176832.0000 | Val MAE: 1050091.6621

Epoch 6/20 [Linear Probing]: 100%|██████████| 277/277 [00:20<00:00, 13.52it/s]

Epoch 6 | Train MSE: 886440182903686.0000 | Val MSE: 14732972744704.0000 | Val MAE: 1032919.4160

Epoch 7/20 [Linear Probing]: 100%|██████████| 277/277 [00:20<00:00, 13.54it/s]

Epoch 7 | Train MSE: 590639351498951.6250 | Val MSE: 8696897044480.0000 | Val MAE: 786849.5029

Epoch 8/20 [Linear Probing]: 100%|██████████| 277/277 [00:20<00:00, 13.52it/s]

Epoch 8 | Train MSE: 407711854408049.6875 | Val MSE: 9005407473664.0000 | Val MAE: 801845.7480
EarlyStopping counter: 1 out of 5

Epoch 9/20 [Linear Probing]: 100%|██████████| 277/277 [00:20<00:00, 13.53it/s]

Epoch 9 | Train MSE: 285327941588703.6250 | Val MSE: 6702445924352.0000 | Val MAE: 692444.1572

Epoch 10/20 [Linear Probing]: 100%|██████████| 277/277 [00:20<00:00, 13.52it/s]

Epoch 10 | Train MSE: 201533142362932.6875 | Val MSE: 5674573000704.0000 | Val MAE: 634782.7236

Epoch 11/20 [Linear Probing]: 100%|██████████| 277/277 [00:20<00:00, 13.52it/s]

Epoch 11 | Train MSE: 141994796483151.4688 | Val MSE: 4778794215424.0000 | Val MAE: 578211.9102

Epoch 12/20 [Linear Probing]: 100%|██████████| 277/277 [00:20<00:00, 13.53it/s]

Epoch 12 | Train MSE: 100548926142500.9688 | Val MSE: 4561019367424.0000 | Val MAE: 567739.2686

Epoch 13/20 [Linear Probing]: 100%|██████████| 277/277 [00:20<00:00, 13.53it/s]

Epoch 13 | Train MSE: 70315624967970.1953 | Val MSE: 4385994401792.0000 | Val MAE: 560078.7148

Epoch 14/20 [Linear Probing]: 100%|██████████| 277/277 [00:20<00:00, 13.54it/s]

Epoch 14 | Train MSE: 49489987009968.5234 | Val MSE: 3886723205120.0000 | Val MAE: 521124.5361

Epoch 15/20 [Linear Probing]: 100%|██████████| 277/277 [00:20<00:00, 13.55it/s]

Epoch 15 | Train MSE: 35144576880743.5078 | Val MSE: 3190835947520.0000 | Val MAE: 464251.1240

Epoch 16/20 [Linear Probing]: 100%|██████████| 277/277 [00:20<00:00, 13.55it/s]

Epoch 16 | Train MSE: 26361392942024.5469 | Val MSE: 3224525056000.0000 | Val MAE: 474330.2793
EarlyStopping counter: 1 out of 5

Epoch 17/20 [Linear Probing]: 100%|██████████| 277/277 [00:20<00:00, 13.52it/s]

Epoch 17 | Train MSE: 20610235312061.4570 | Val MSE: 4514820581376.0000 | Val MAE: 540777.9512
EarlyStopping counter: 2 out of 5

Epoch 18/20 [Linear Probing]: 100%|██████████| 277/277 [00:20<00:00, 13.55it/s]

Epoch 18 | Train MSE: 20162173381606.1211 | Val MSE: 6389162917888.0000 | Val MAE: 631669.3242
EarlyStopping counter: 3 out of 5

Epoch 19/20 [Linear Probing]: 100%|██████████| 277/277 [00:20<00:00, 13.53it/s]

Epoch 19 | Train MSE: 15362177284783.5957 | Val MSE: 4193777457152.0000 | Val MAE: 535571.0430
EarlyStopping counter: 4 out of 5

Epoch 20/20 [Linear Probing]: 100%|██████████| 277/277 [00:20<00:00, 13.55it/s]

Epoch 20 | Train MSE: 18312251350773.8320 | Val MSE: 3161693235200.0000 | Val MAE: 443612.6704

FINAL RESULTS (WEATHER)
              Val MSE     Val MAE
Horizon
96       3.118930e+12  453282.287
192      2.146466e+12  369374.516
336      9.753807e+12  674987.046
720      3.161693e+12  443612.670

In [ ]:
print("=== PREPROCESSING ELECTRICITY DATA ===")
ELECTRICITY_DIR = f"{BASE_DIR}/electricity_data"
file_path = os.path.join(ELECTRICITY_DIR, "LD2011_2014.txt")
df_elec_raw = pd.read_csv(file_path, sep=';', decimal=',', low_memory=False)
time_col = df_elec_raw.columns[0]
df_elec = df_elec_raw.copy()
df_elec[time_col] = pd.to_datetime(df_elec[time_col].astype(str).str.strip(), errors="coerce")
df_elec = df_elec.dropna(subset=[time_col]).sort_values(time_col).reset_index(drop=True)

elec_train_end = int(len(df_elec) * 0.7)
elec_val_end = int(len(df_elec) * 0.8)
train_df_elec = df_elec.iloc[:elec_train_end]
val_df_elec = df_elec.iloc[elec_train_end:elec_val_end]
elec_features = [c for c in df_elec.columns if c != time_col]

print("\n=== PHASE 1: Self-Supervised Pre-Training (Electricity) ===")
seq_len, batch_size = 512, 32
train_dataset_elec_ssl = WeatherDataset(train_df_elec[elec_features], seq_len, pred_len=96)
val_dataset_elec_ssl = WeatherDataset(val_df_elec[elec_features], seq_len, pred_len=96)
train_loader_elec_ssl = DataLoader(train_dataset_elec_ssl, batch_size=batch_size, shuffle=True, drop_last=True)
val_loader_elec_ssl = DataLoader(val_dataset_elec_ssl, batch_size=batch_size, shuffle=False)

model_ssl_elec = PatchTST_SelfSupervised(num_features=len(elec_features), seq_len=seq_len, patch_len=12, stride=12)
trained_ssl_model_elec = pretrain_model_with_es(model_ssl_elec, train_loader_elec_ssl, val_loader_elec_ssl, epochs=100, lr=1e-4, patience=10)

print("\n=== PHASE 2: Linear Probing (Electricity) ===")
results_summary_elec = {"Horizon": [], "Val MSE": [], "Val MAE": []}
for pred_len in [96, 192, 336, 720]:
    print(f"\n--- Horizon: T={pred_len} ---")
    train_loader = DataLoader(WeatherDataset(train_df_elec[elec_features], seq_len, pred_len), batch_size=batch_size, shuffle=True, drop_last=True)
    val_loader = DataLoader(WeatherDataset(val_df_elec[elec_features], seq_len, pred_len), batch_size=batch_size, shuffle=False)

    model_sup_elec = PatchTST_Supervised(num_features=len(elec_features), seq_len=seq_len, pred_len=pred_len, patch_len=12, stride=12)
    trained_sup_model_elec = linear_probing_with_es(model_sup_elec, trained_ssl_model_elec, train_loader, val_loader, epochs=20, lr=1e-4, patience=5)

    trained_sup_model_elec.eval()
    v_mse, v_mae = 0.0, 0.0
    with torch.no_grad():
        for bx, by in val_loader:
            bx, by = bx.to(device), by.to(device)
            preds = trained_sup_model_elec(bx)
            v_mse += nn.MSELoss()(preds, by).item()
            v_mae += nn.L1Loss()(preds, by).item()

    results_summary_elec["Horizon"].append(pred_len)
    results_summary_elec["Val MSE"].append(v_mse / len(val_loader))
    results_summary_elec["Val MAE"].append(v_mae / len(val_loader))

print("\nFINAL RESULTS (ELECTRICITY)")
print(pd.DataFrame(results_summary_elec).set_index("Horizon").round(3))

=== PREPROCESSING ELECTRICITY DATA ===

=== PHASE 1: Self-Supervised Pre-Training (Electricity) ===

Epoch 1/100 [Pre-train]: 100%|██████████| 3049/3049 [46:10<00:00,  1.10it/s]

Epoch 1 | Train Loss: 0.1852 | Val Loss: 0.1169

Epoch 2/100 [Pre-train]: 100%|██████████| 3049/3049 [46:44<00:00,  1.09it/s]

Epoch 2 | Train Loss: 0.0615 | Val Loss: 0.0553

Epoch 3/100 [Pre-train]: 100%|██████████| 3049/3049 [46:44<00:00,  1.09it/s]

Epoch 3 | Train Loss: 0.0234 | Val Loss: 0.0270

Epoch 4/100 [Pre-train]: 100%|██████████| 3049/3049 [46:44<00:00,  1.09it/s]

Epoch 4 | Train Loss: 0.0058 | Val Loss: 0.0172

Epoch 5/100 [Pre-train]: 100%|██████████| 3049/3049 [46:44<00:00,  1.09it/s]

Epoch 5 | Train Loss: 0.0005 | Val Loss: 0.0171

Epoch 6/100 [Pre-train]: 100%|██████████| 3049/3049 [46:44<00:00,  1.09it/s]

Epoch 6 | Train Loss: 0.0000 | Val Loss: 0.0155

Epoch 7/100 [Pre-train]: 100%|██████████| 3049/3049 [46:44<00:00,  1.09it/s]

Epoch 7 | Train Loss: 0.0000 | Val Loss: 0.0164
EarlyStopping counter: 1 out of 10

Epoch 8/100 [Pre-train]: 100%|██████████| 3049/3049 [46:39<00:00,  1.09it/s]

Epoch 8 | Train Loss: 0.0000 | Val Loss: 0.0183
EarlyStopping counter: 2 out of 10

Epoch 9/100 [Pre-train]: 100%|██████████| 3049/3049 [46:27<00:00,  1.09it/s]

Epoch 9 | Train Loss: 0.0000 | Val Loss: 0.0202
EarlyStopping counter: 3 out of 10

Epoch 10/100 [Pre-train]: 100%|██████████| 3049/3049 [46:27<00:00,  1.09it/s]

Epoch 10 | Train Loss: 0.0000 | Val Loss: 0.0211
EarlyStopping counter: 4 out of 10

Epoch 11/100 [Pre-train]: 100%|██████████| 3049/3049 [46:30<00:00,  1.09it/s]

Epoch 11 | Train Loss: 0.0000 | Val Loss: 0.0216
EarlyStopping counter: 5 out of 10

Epoch 12/100 [Pre-train]: 100%|██████████| 3049/3049 [46:40<00:00,  1.09it/s]

Epoch 12 | Train Loss: 0.0000 | Val Loss: 0.0217
EarlyStopping counter: 6 out of 10

Epoch 13/100 [Pre-train]: 100%|██████████| 3049/3049 [46:44<00:00,  1.09it/s]

Epoch 13 | Train Loss: 0.0000 | Val Loss: 0.0217
EarlyStopping counter: 7 out of 10

Epoch 14/100 [Pre-train]: 100%|██████████| 3049/3049 [46:44<00:00,  1.09it/s]

Epoch 14 | Train Loss: 0.0000 | Val Loss: 0.0217
EarlyStopping counter: 8 out of 10

Epoch 15/100 [Pre-train]:  37%|███▋      | 1123/3049 [17:12<29:32,  1.09it/s]